### ISSUE TITLE
Getting Alexa Errors in HA

### ISSUE THREAD

**Issue by bachoo786** [keatontaylor/alexa-actions#109]
Hi there

I have followed your instructions to make this work for me. However when I trigger my automation, Alexa does not say anything and in my HA log I have the following Login errors. Can someone please help? Thanks.

```
2022-04-16 14:01:52 WARNING (MainThread) [alexapy.helpers] alexaapi.run_behavior((<alexapy.alexaapi.AlexaAPI object at 0x7faec00d05e0>, {'@type': 'com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode', 'type': 'Alexa.Operation.SkillConnections.Launch', 'operationPayload': {'targetDevice': {'deviceType': 'A3VRME03NAXFUB', 'device>
('Login error detected; not contacting API',)
2022-04-16 14:01:52 WARNING (MainThread) [alexapy.helpers] alexaapi.run_skill((<alexapy.alexaapi.AlexaAPI object at 0x7faec00d05e0>, 'amzn1.ask.skill.d82ede2c-8bb4-42b9-bc8c-aa67b50c2263'), {'queue_delay': 1.5}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2022-04-16 14:01:52 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 520, in run_skill
    await self.run_behavior(node_data, queue_delay=queue_delay)
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 398, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 202, in _post_request
    return await self._request("post", uri, data)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 172, in _request
    raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API

```

**Comment by DEADSEC-SECURITY** [comment]
This is not exactly an error for this repo but try uninstalling or resetting the library should allow for you to refresh the login tokens
