### ISSUE TITLE
Skill response was marked as failure

### ISSUE THREAD

**Issue by mirlorojiblanco** [keatontaylor/alexa-actions#123]
I am quite desperate. I followed step by step the new skill in Alexa developer and connected to my HA but I receive the following error:
Skill response was marked as failure

The target Lambda application returned a failure response

At the beginning the skill worked but after somes test the error appeared.

Please the help is welcome

**Comment by rlust** [comment]
Same problem here, I have tried detailed instructions 2 time and I still get "There was a problem with the requested skills response"

**Comment by flopaphome** [comment]
same here

**Comment by mirlorojiblanco** [comment]
Please, I am desperate :-(
Can anybody provide some clues about what the problem is ?

**Comment by DEADSEC-SECURITY** [comment]
Can you share the logs @mirlorojiblanco

**Comment by mirlorojiblanco** [comment]
Hi,
I fix the issue!!!!!. My alexa is using Spanish (ES) but in the language_strings.json file doesn't was included the spanisj section. After adding "es" section it works so I suppose this was the reason of the error message.

**Comment by flopaphome** [comment]
i still get the error like rlust.
any clues?

**Comment by flopaphome** [comment]
which logs? how?

**Comment by DEADSEC-SECURITY** [comment]
Cloudwhatch logs.

**Comment by flopaphome** [comment]
cloudwatch?

**Comment by flopaphome** [comment]
Die spezifische Protokollgruppe: /aws/lambda/4cb18c36-69bc-4745-9b03-b3d1dd627ef1 ist in diesem Konto oder dieser Region nicht vorhanden.

The specific log group does not exist in this account or region.

**Comment by DEADSEC-SECURITY** [comment]
Did you select the correct region for AWS?

**Comment by flopaphome** [comment]
where?

**Comment by flopaphome** [comment]
eu-west-1
ireland

**Comment by flopaphome** [comment]
is this it?

2022-09-19T22:53:38.484+02:00Kopieren[ERROR] NameError: name 'true' is not definedTraceback (most recent call last):  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module    return load_source(name, filename, file)  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source    module = _load(spec)  File "<frozen importlib._bootstrap>", line 696, in _load  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked  File "<frozen importlib._bootstrap_external>", line 728, in exec_module  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed  File "/var/task/lambda_function.py", line 6, in <module>    VERIFY_SSL = true  # SET TO FALSE IF YOU DO NOT HAVE VALID CERTS | [ERROR] NameError: name 'true' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 728, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/task/lambda_function.py", line 6, in <module>     VERIFY_SSL = true # SET TO FALSE IF YOU DO NOT HAVE VALID CERTS
-- | --

**Comment by DEADSEC-SECURITY** [comment]
Please read the logs before asking me to do so!
`[ERROR] NameError: name 'true' is not defined` with a simple google search -> [StackOverflow](https://stackoverflow.com/questions/30095032/nameerror-name-true-is-not-defined) -> true needs to be capitalized -> True instead of true
