### ISSUE TITLE
[Bug]: Unable to add skill using linked account / token

### ISSUE THREAD

**Issue by vdominguez87** [keatontaylor/alexa-actions#222]
### Did you check our FAQ and Issue/PR for similar issues?

- [X] FAQ checked!
- [X] Issues/PR checked!

### Contact Details

vdominguez87@gmail.com

### What happened?

A bug happened!

### Version

Latest

### What Alexa device are you using?

Echo, Echo Show

### Relevant log output

```shell
2024-01-13T09:58:57.681-08:00

Copy
ha_obj.post_ha_event(RESPONSE_NONE, RESPONSE_NONE)
ha_obj.post_ha_event(RESPONSE_NONE, RESPONSE_NONE)

2024-01-13T09:58:57.681-08:00	File "/var/task/lambda_function.py", line 315, in post_ha_event

2024-01-13T09:58:57.681-08:00	body = {"event_id": self.ha_state.event_id, "event_response": response, "event_response_type": response_type}

2024-01-13T09:58:57.681-08:00	AttributeError: 'HaStateError' object has no attribute 'event_id'

2024-01-13T09:58:57.681-08:00	[ERROR] 2024-01-13T17:58:57.680Z 6d96bb49-32e8-45d0-bdbc-7188a9eec944 'HaStateError' object has no attribute 'event_id'

2024-01-13T09:58:57.681-08:00	Traceback (most recent call last):

2024-01-13T09:58:57.681-08:00	File "/var/task/ask_sdk_runtime/dispatch.py", line 118, in dispatch
```

**Comment by vdominguez87** [comment]
Just a headsup because this looks to be relatively well maintained but this is no longer working, for a lot of people. Cheers

**Comment by Joeslinky** [comment]
I'm also having issues, just today it's started saying "Sorry, I did not catch that"

**Comment by DEADSEC-SECURITY** [comment]
Hmm interesting, this looks like a bug actually.

**Comment by DEADSEC-SECURITY** [comment]
Can you activate debug mode and see if you get the error again so i can see all the logs?

**Comment by DEADSEC-SECURITY** [comment]
Please check the latests release
