### ISSUE TITLE
Subsequent requests fail

### ISSUE THREAD

**Issue by Siege36** [keatontaylor/alexa-actions#34]
After deploying code in the alexa console, I can make 1 request and respond with a number. Further requests fail with Alexa responding "Sorry, I had trouble doing what you asked, or couldn't understand you. Please try again." 
Debug logs:
```
15:53:55    REPORT RequestId: bd030ce8-f179-4ab1-80f9-ac689d3f61e4 Duration: 3.90 ms Billed Duration: 100 ms Memory Size: 512 MB Max Memory Used: 59 MB
15:54:07    START RequestId: 34fe72fe-c332-4a76-ab3e-1d1f6bd8d02b Version: 2
15:54:07    CatchAllExceptionHandler
15:54:07    [ERROR] 2020-05-19T15:54:07.884Z 34fe72fe-c332-4a76-ab3e-1d1f6bd8d02b 'NoneType' object is not subscriptable
15:54:07    Traceback (most recent call last):  Traceback (most recent call last):
15:54:07    File "/var/task/ask_sdk_runtime/dispatch.py", line 118, in dispatch
15:54:07    output = self.__dispatch_request(handler_input) # type: Union[Output, None]
15:54:07    File "/var/task/ask_sdk_runtime/dispatch.py", line 183, in __dispatch_request
15:54:07    handler_input=handler_input, handler=request_handler) # type: Union[Output, None]
15:54:07    File "/var/task/ask_sdk_runtime/dispatch_components/request_components.py", line 437, in execute
15:54:07    return handler.handle(handler_input)
15:54:07    File "/var/task/lambda_function.py", line 312, in handle
15:54:07    speak_output = home_assistant_object.post_ha_event(RESPONSE_NONE, RESPONSE_NONE)
15:54:07    File "/var/task/lambda_function.py", line 120, in post_ha_event
15:54:07    "event_id": self.ha_state['event_id'],
15:54:07    TypeError: 'NoneType' object is not subscriptable
15:54:07    END RequestId: 34fe72fe-c332-4a76-ab3e-1d1f6bd8d02b
```

**Comment by Siege36** [comment]
resolved in 7.1
