### ISSUE TITLE
"Error: invalid client id or redirect uri" when linking account

### ISSUE THREAD

**Issue by ripvega** [keatontaylor/alexa-actions#35]
I'm seeing the above error when attempting to link the skill to HA. (Yes, it does say uri not URL).

In HA I'm seeing the following, possibly related, errors:

```
Logger: hass_nabucasa.cloud_api
Source: components/cloud/alexa_config.py:114
First occurred: 8:02:46 AM (3 occurrences)
Last logged: 8:02:46 AM

Fetched https://alexa-api.nabucasa.com/access_token (400)
```
and
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 295, in _handle_entity_registry_updated
    await self._sync_helper(to_update, to_remove)
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 239, in _sync_helper
    await self.async_get_access_token()
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 128, in async_get_access_token
    raise RequireRelink
homeassistant.components.cloud.const.RequireRelink
```
The URL amazon tries to direct to when requesting linking does contain the correct NabuCasa remote access URL for my HA instance.

Any pointers you can give me will be much appreciated.

**Comment by keatontaylor** [comment]
Generally this is due to the client ID not matching the redirect URL provided by amazon. If you do account linking via the Alexa web browser page, when it redirects to home assistant, you can copy the link in your browsers address bar. 

The redirect_url in the link is the one that needs to be provided in the client ID for the custom skill

**Comment by ripvega** [comment]
Thank you, Keaton. I had to use .com instead of .co.uk to get this to work.

However, the only part now not working is I don't hear anything from Alexa. 

When HA changes state, the message changes accordingly if I say "open custom actions" but it doesn't say that in response to the HA state change.

After me saying "open custom actions" I get the follow on option and after saying "yes" it makes the change in HA.

I just don't get the "heating has been turned on", for example, without me saying "open custom actions".

There's a disconnect somewhere and I'm now lost as to where to look for it.

BTW. This is excellent work and I appreciate your time. Thank you.

**Comment by flix4f** [comment]
I seem to be stuck at the same point. Using NabuCasa address for front end access and get to the login page but get the "invalid client id or..." there.

**You're about to give https://layla.amazon.com/ access to your Home Assistant instance.

Logging in with Home Assistant Local.
Error: invalid client id or redirect uri**

**Comment by keatontaylor** [comment]
@flix4f are you still having issues, or were you able to get past this?

**Comment by sp3cialck** [comment]
I'm having the same issue!!

**Comment by kaareseras** [comment]
Any news on this issue?

Im living in Denmark, and I have tried to build the skill both in n.virginia and Ireland, but in both cases I get the Ivalid client ID error.

Please help
